services:
    postgres:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user_role_db
        ports:
            - "5432:5432"
        restart: unless-stopped
